#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 154
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_pub = 1,
  anon_sym_fn = 2,
  anon_sym_LPAREN = 3,
  anon_sym_COMMA = 4,
  anon_sym_RPAREN = 5,
  anon_sym_COLON = 6,
  anon_sym_comptime = 7,
  anon_sym_LBRACE = 8,
  anon_sym_RBRACE = 9,
  anon_sym_let = 10,
  anon_sym_EQ = 11,
  anon_sym_SEMI = 12,
  anon_sym_if = 13,
  anon_sym_else = 14,
  anon_sym_STAR = 15,
  anon_sym_PLUS = 16,
  anon_sym_DASH = 17,
  anon_sym_EQ_EQ = 18,
  anon_sym_AT = 19,
  anon_sym_struct = 20,
  anon_sym_DOT = 21,
  sym_name = 22,
  sym_integer_literal = 23,
  anon_sym_true = 24,
  anon_sym_false = 25,
  sym_source_file = 26,
  sym_decl = 27,
  sym_fn_decl = 28,
  sym_field_decl = 29,
  sym_param = 30,
  sym_block = 31,
  sym_stmt = 32,
  sym_let_ = 33,
  sym_arg_list = 34,
  sym_expr = 35,
  sym_boolean_literal = 36,
  sym_constructor_block = 37,
  sym_constructor_field = 38,
  aux_sym_source_file_repeat1 = 39,
  aux_sym_fn_decl_repeat1 = 40,
  aux_sym_block_repeat1 = 41,
  aux_sym_arg_list_repeat1 = 42,
  aux_sym_constructor_block_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_pub] = "pub",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_comptime] = "comptime",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_STAR] = "*",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_AT] = "@",
  [anon_sym_struct] = "struct",
  [anon_sym_DOT] = ".",
  [sym_name] = "name",
  [sym_integer_literal] = "integer_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym_decl] = "decl",
  [sym_fn_decl] = "fn_decl",
  [sym_field_decl] = "field_decl",
  [sym_param] = "param",
  [sym_block] = "block",
  [sym_stmt] = "stmt",
  [sym_let_] = "let_",
  [sym_arg_list] = "arg_list",
  [sym_expr] = "expr",
  [sym_boolean_literal] = "boolean_literal",
  [sym_constructor_block] = "constructor_block",
  [sym_constructor_field] = "constructor_field",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_fn_decl_repeat1] = "fn_decl_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_arg_list_repeat1] = "arg_list_repeat1",
  [aux_sym_constructor_block_repeat1] = "constructor_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_pub] = anon_sym_pub,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_comptime] = anon_sym_comptime,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_struct] = anon_sym_struct,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_name] = sym_name,
  [sym_integer_literal] = sym_integer_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym_decl] = sym_decl,
  [sym_fn_decl] = sym_fn_decl,
  [sym_field_decl] = sym_field_decl,
  [sym_param] = sym_param,
  [sym_block] = sym_block,
  [sym_stmt] = sym_stmt,
  [sym_let_] = sym_let_,
  [sym_arg_list] = sym_arg_list,
  [sym_expr] = sym_expr,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_constructor_block] = sym_constructor_block,
  [sym_constructor_field] = sym_constructor_field,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_fn_decl_repeat1] = aux_sym_fn_decl_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_arg_list_repeat1] = aux_sym_arg_list_repeat1,
  [aux_sym_constructor_block_repeat1] = aux_sym_constructor_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_pub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_comptime] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_struct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_fn_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_field_decl] = {
    .visible = true,
    .named = true,
  },
  [sym_param] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_let_] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_list] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_constructor_block] = {
    .visible = true,
    .named = true,
  },
  [sym_constructor_field] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fn_decl_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arg_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_constructor_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 22,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 39,
  [47] = 47,
  [48] = 24,
  [49] = 49,
  [50] = 50,
  [51] = 45,
  [52] = 36,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 55,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 63,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 64,
  [75] = 70,
  [76] = 76,
  [77] = 73,
  [78] = 68,
  [79] = 79,
  [80] = 80,
  [81] = 79,
  [82] = 71,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 86,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 92,
  [95] = 95,
  [96] = 95,
  [97] = 91,
  [98] = 98,
  [99] = 93,
  [100] = 100,
  [101] = 8,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 104,
  [107] = 107,
  [108] = 108,
  [109] = 107,
  [110] = 7,
  [111] = 103,
  [112] = 100,
  [113] = 105,
  [114] = 114,
  [115] = 115,
  [116] = 115,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 119,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 124,
  [127] = 123,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 139,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
  [146] = 146,
  [147] = 147,
  [148] = 148,
  [149] = 134,
  [150] = 143,
  [151] = 140,
  [152] = 133,
  [153] = 136,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '*') ADVANCE(28);
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == ',') ADVANCE(16);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == ';') ADVANCE(24);
      if (lookahead == '=') ADVANCE(23);
      if (lookahead == '@') ADVANCE(32);
      if (lookahead == 'c') ADVANCE(51);
      if (lookahead == 'e') ADVANCE(46);
      if (lookahead == 'f') ADVANCE(35);
      if (lookahead == 'i') ADVANCE(44);
      if (lookahead == 'l') ADVANCE(43);
      if (lookahead == 'p') ADVANCE(61);
      if (lookahead == 's') ADVANCE(60);
      if (lookahead == 't') ADVANCE(53);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '@') ADVANCE(32);
      if (lookahead == 'c') ADVANCE(51);
      if (lookahead == 'f') ADVANCE(36);
      if (lookahead == 'i') ADVANCE(44);
      if (lookahead == 's') ADVANCE(60);
      if (lookahead == 't') ADVANCE(53);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == 'c') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 3:
      if (lookahead == '@') ADVANCE(32);
      if (lookahead == 'c') ADVANCE(51);
      if (lookahead == 'f') ADVANCE(36);
      if (lookahead == 'i') ADVANCE(44);
      if (lookahead == 'l') ADVANCE(43);
      if (lookahead == 's') ADVANCE(60);
      if (lookahead == 't') ADVANCE(53);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(6);
      if (lookahead == 'f') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      END_STATE();
    case 5:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 6:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 8:
      if (lookahead == 's') ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '(') ADVANCE(15);
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '*') ADVANCE(28);
      if (lookahead == '+') ADVANCE(29);
      if (lookahead == ',') ADVANCE(16);
      if (lookahead == '-') ADVANCE(30);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == ';') ADVANCE(24);
      if (lookahead == '=') ADVANCE(23);
      if (lookahead == 'f') ADVANCE(50);
      if (lookahead == 'p') ADVANCE(61);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(21);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(10)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_pub);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_comptime);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_else);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_struct);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'a') ADVANCE(47);
      if (lookahead == 'n') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'a') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'b') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'c') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'f') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'i') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'l') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'l') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'm') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'm') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'n') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'o') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'p') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'r') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'r') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 's') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 's') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 't') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 't') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 't') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 't') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'u') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'u') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'u') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 10},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 10},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 10},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 10},
  [87] = {.lex_state = 10},
  [88] = {.lex_state = 10},
  [89] = {.lex_state = 10},
  [90] = {.lex_state = 10},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 10},
  [101] = {.lex_state = 10},
  [102] = {.lex_state = 9},
  [103] = {.lex_state = 10},
  [104] = {.lex_state = 10},
  [105] = {.lex_state = 10},
  [106] = {.lex_state = 10},
  [107] = {.lex_state = 10},
  [108] = {.lex_state = 9},
  [109] = {.lex_state = 10},
  [110] = {.lex_state = 10},
  [111] = {.lex_state = 10},
  [112] = {.lex_state = 10},
  [113] = {.lex_state = 10},
  [114] = {.lex_state = 9},
  [115] = {.lex_state = 10},
  [116] = {.lex_state = 10},
  [117] = {.lex_state = 2},
  [118] = {.lex_state = 9},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 9},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 9},
  [133] = {.lex_state = 9},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 4},
  [136] = {.lex_state = 4},
  [137] = {.lex_state = 9},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 9},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 9},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 9},
  [152] = {.lex_state = 9},
  [153] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_pub] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_comptime] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_struct] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(138),
    [sym_decl] = STATE(89),
    [sym_fn_decl] = STATE(116),
    [sym_field_decl] = STATE(116),
    [aux_sym_source_file_repeat1] = STATE(89),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_pub] = ACTIONS(5),
    [anon_sym_fn] = ACTIONS(7),
    [sym_name] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      sym_name,
    ACTIONS(27), 1,
      sym_integer_literal,
    STATE(61), 1,
      sym_let_,
    STATE(79), 1,
      sym_expr,
    STATE(114), 1,
      aux_sym_constructor_block_repeat1,
    STATE(121), 1,
      sym_constructor_field,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_stmt,
      aux_sym_block_repeat1,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [52] = 16,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      sym_name,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      sym_let_,
    STATE(81), 1,
      sym_expr,
    STATE(114), 1,
      aux_sym_constructor_block_repeat1,
    STATE(121), 1,
      sym_constructor_field,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym_stmt,
      aux_sym_block_repeat1,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [104] = 14,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(35), 1,
      sym_name,
    STATE(61), 1,
      sym_let_,
    STATE(78), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(14), 2,
      sym_stmt,
      aux_sym_block_repeat1,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [150] = 14,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      sym_let_,
    STATE(68), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(14), 2,
      sym_stmt,
      aux_sym_block_repeat1,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [196] = 14,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_let,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    STATE(61), 1,
      sym_let_,
    STATE(81), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym_stmt,
      aux_sym_block_repeat1,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [242] = 2,
    ACTIONS(43), 4,
      anon_sym_pub,
      anon_sym_fn,
      anon_sym_EQ,
      sym_name,
    ACTIONS(41), 12,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [263] = 2,
    ACTIONS(47), 4,
      anon_sym_pub,
      anon_sym_fn,
      anon_sym_EQ,
      sym_name,
    ACTIONS(45), 12,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [284] = 13,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(25), 1,
      sym_name,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(83), 1,
      sym_expr,
    STATE(114), 1,
      aux_sym_constructor_block_repeat1,
    STATE(121), 1,
      sym_constructor_field,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [326] = 12,
    ACTIONS(51), 1,
      anon_sym_RPAREN,
    ACTIONS(53), 1,
      anon_sym_comptime,
    ACTIONS(56), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      anon_sym_if,
    ACTIONS(62), 1,
      anon_sym_AT,
    ACTIONS(65), 1,
      anon_sym_struct,
    ACTIONS(68), 1,
      sym_name,
    ACTIONS(71), 1,
      sym_integer_literal,
    STATE(10), 1,
      aux_sym_arg_list_repeat1,
    STATE(69), 1,
      sym_expr,
    ACTIONS(74), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [365] = 12,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
    STATE(10), 1,
      aux_sym_arg_list_repeat1,
    STATE(60), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [404] = 5,
    ACTIONS(81), 1,
      anon_sym_EQ,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
    ACTIONS(79), 8,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [429] = 4,
    ACTIONS(81), 1,
      anon_sym_EQ,
    ACTIONS(83), 1,
      anon_sym_STAR,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
    ACTIONS(79), 10,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [452] = 5,
    ACTIONS(91), 1,
      anon_sym_let,
    STATE(61), 1,
      sym_let_,
    STATE(14), 2,
      sym_stmt,
      aux_sym_block_repeat1,
    ACTIONS(89), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_integer_literal,
    ACTIONS(87), 6,
      anon_sym_comptime,
      anon_sym_if,
      anon_sym_struct,
      sym_name,
      anon_sym_true,
      anon_sym_false,
  [477] = 3,
    ACTIONS(81), 1,
      anon_sym_EQ,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
    ACTIONS(79), 11,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [498] = 12,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    ACTIONS(94), 1,
      anon_sym_RPAREN,
    STATE(11), 1,
      aux_sym_arg_list_repeat1,
    STATE(62), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [537] = 6,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(98), 1,
      anon_sym_EQ,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
    ACTIONS(96), 7,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_DOT,
  [564] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(76), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [597] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(17), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [630] = 2,
    ACTIONS(104), 1,
      anon_sym_EQ,
    ACTIONS(102), 11,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [647] = 2,
    ACTIONS(108), 1,
      anon_sym_EQ,
    ACTIONS(106), 11,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [664] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(64), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [697] = 2,
    ACTIONS(112), 1,
      anon_sym_EQ,
    ACTIONS(110), 11,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [714] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(67), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [747] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(57), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [780] = 2,
    ACTIONS(116), 1,
      anon_sym_EQ,
    ACTIONS(114), 11,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [797] = 2,
    ACTIONS(120), 1,
      anon_sym_EQ,
    ACTIONS(118), 11,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [814] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(74), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [847] = 2,
    ACTIONS(124), 1,
      anon_sym_EQ,
    ACTIONS(122), 11,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [864] = 2,
    ACTIONS(128), 1,
      anon_sym_EQ,
    ACTIONS(126), 11,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [881] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(65), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [914] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(66), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [947] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(85), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [980] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(58), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [1013] = 2,
    ACTIONS(132), 1,
      anon_sym_EQ,
    ACTIONS(130), 11,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [1030] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(70), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [1063] = 2,
    ACTIONS(136), 1,
      anon_sym_EQ,
    ACTIONS(134), 11,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [1080] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(80), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [1113] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(71), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [1146] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(15), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [1179] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(13), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [1212] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(12), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [1245] = 2,
    ACTIONS(140), 1,
      anon_sym_EQ,
    ACTIONS(138), 11,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [1262] = 2,
    ACTIONS(98), 1,
      anon_sym_EQ,
    ACTIONS(96), 11,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [1279] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(73), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [1312] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(82), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [1345] = 2,
    ACTIONS(81), 1,
      anon_sym_EQ,
    ACTIONS(79), 11,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [1362] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(63), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [1395] = 2,
    ACTIONS(144), 1,
      anon_sym_EQ,
    ACTIONS(142), 11,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [1412] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(54), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [1445] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(77), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [1478] = 10,
    ACTIONS(11), 1,
      anon_sym_comptime,
    ACTIONS(13), 1,
      anon_sym_LBRACE,
    ACTIONS(19), 1,
      anon_sym_if,
    ACTIONS(21), 1,
      anon_sym_AT,
    ACTIONS(23), 1,
      anon_sym_struct,
    ACTIONS(27), 1,
      sym_integer_literal,
    ACTIONS(35), 1,
      sym_name,
    STATE(75), 1,
      sym_expr,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(20), 2,
      sym_block,
      sym_boolean_literal,
  [1511] = 2,
    ACTIONS(148), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_integer_literal,
    ACTIONS(146), 7,
      anon_sym_comptime,
      anon_sym_let,
      anon_sym_if,
      anon_sym_struct,
      sym_name,
      anon_sym_true,
      anon_sym_false,
  [1527] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(152), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [1555] = 3,
    ACTIONS(122), 1,
      anon_sym_RBRACE,
    ACTIONS(124), 3,
      anon_sym_pub,
      anon_sym_fn,
      sym_name,
    ACTIONS(134), 7,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [1573] = 2,
    ACTIONS(160), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_integer_literal,
    ACTIONS(158), 7,
      anon_sym_comptime,
      anon_sym_let,
      anon_sym_if,
      anon_sym_struct,
      sym_name,
      anon_sym_true,
      anon_sym_false,
  [1589] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(162), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [1617] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(164), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [1645] = 3,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
    ACTIONS(124), 3,
      anon_sym_pub,
      anon_sym_fn,
      sym_name,
    ACTIONS(134), 7,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [1663] = 9,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    ACTIONS(168), 1,
      anon_sym_RPAREN,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [1693] = 2,
    ACTIONS(172), 4,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_AT,
      sym_integer_literal,
    ACTIONS(170), 7,
      anon_sym_comptime,
      anon_sym_let,
      anon_sym_if,
      anon_sym_struct,
      sym_name,
      anon_sym_true,
      anon_sym_false,
  [1709] = 9,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [1739] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(174), 1,
      anon_sym_LBRACE,
    STATE(109), 1,
      sym_block,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [1766] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(176), 1,
      anon_sym_LBRACE,
    STATE(111), 1,
      sym_block,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [1793] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(178), 1,
      anon_sym_SEMI,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [1820] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(180), 1,
      anon_sym_EQ,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [1847] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(176), 1,
      anon_sym_LBRACE,
    STATE(107), 1,
      sym_block,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [1874] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [1901] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(166), 1,
      anon_sym_COMMA,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [1928] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(176), 1,
      anon_sym_LBRACE,
    STATE(106), 1,
      sym_block,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [1955] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(184), 1,
      anon_sym_COMMA,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [1982] = 2,
    ACTIONS(51), 4,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_AT,
      sym_integer_literal,
    ACTIONS(186), 6,
      anon_sym_comptime,
      anon_sym_if,
      anon_sym_struct,
      sym_name,
      anon_sym_true,
      anon_sym_false,
  [1997] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(176), 1,
      anon_sym_LBRACE,
    STATE(113), 1,
      sym_block,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [2024] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(174), 1,
      anon_sym_LBRACE,
    STATE(103), 1,
      sym_block,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [2051] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(174), 1,
      anon_sym_LBRACE,
    STATE(104), 1,
      sym_block,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [2078] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(188), 1,
      anon_sym_SEMI,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [2105] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(174), 1,
      anon_sym_LBRACE,
    STATE(105), 1,
      sym_block,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [2132] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [2159] = 8,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [2186] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [2213] = 8,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [2240] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(194), 1,
      anon_sym_COMMA,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [2267] = 8,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [2294] = 2,
    ACTIONS(198), 1,
      anon_sym_COLON,
    ACTIONS(102), 8,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_STAR,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_DOT,
  [2308] = 7,
    ACTIONS(83), 1,
      anon_sym_STAR,
    ACTIONS(100), 1,
      anon_sym_EQ_EQ,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    ACTIONS(156), 1,
      anon_sym_DOT,
    ACTIONS(200), 1,
      anon_sym_LBRACE,
    ACTIONS(85), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(44), 2,
      sym_arg_list,
      sym_constructor_block,
  [2332] = 6,
    ACTIONS(202), 1,
      anon_sym_pub,
    ACTIONS(205), 1,
      anon_sym_fn,
    ACTIONS(208), 1,
      anon_sym_RBRACE,
    ACTIONS(210), 1,
      sym_name,
    STATE(86), 2,
      sym_decl,
      aux_sym_source_file_repeat1,
    STATE(115), 2,
      sym_fn_decl,
      sym_field_decl,
  [2353] = 6,
    ACTIONS(208), 1,
      ts_builtin_sym_end,
    ACTIONS(213), 1,
      anon_sym_pub,
    ACTIONS(216), 1,
      anon_sym_fn,
    ACTIONS(219), 1,
      sym_name,
    STATE(87), 2,
      sym_decl,
      aux_sym_source_file_repeat1,
    STATE(116), 2,
      sym_fn_decl,
      sym_field_decl,
  [2374] = 6,
    ACTIONS(222), 1,
      anon_sym_pub,
    ACTIONS(224), 1,
      anon_sym_fn,
    ACTIONS(226), 1,
      anon_sym_RBRACE,
    ACTIONS(228), 1,
      sym_name,
    STATE(90), 2,
      sym_decl,
      aux_sym_source_file_repeat1,
    STATE(115), 2,
      sym_fn_decl,
      sym_field_decl,
  [2395] = 6,
    ACTIONS(5), 1,
      anon_sym_pub,
    ACTIONS(7), 1,
      anon_sym_fn,
    ACTIONS(9), 1,
      sym_name,
    ACTIONS(230), 1,
      ts_builtin_sym_end,
    STATE(87), 2,
      sym_decl,
      aux_sym_source_file_repeat1,
    STATE(116), 2,
      sym_fn_decl,
      sym_field_decl,
  [2416] = 6,
    ACTIONS(222), 1,
      anon_sym_pub,
    ACTIONS(224), 1,
      anon_sym_fn,
    ACTIONS(228), 1,
      sym_name,
    ACTIONS(232), 1,
      anon_sym_RBRACE,
    STATE(86), 2,
      sym_decl,
      aux_sym_source_file_repeat1,
    STATE(115), 2,
      sym_fn_decl,
      sym_field_decl,
  [2437] = 5,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    ACTIONS(236), 1,
      anon_sym_comptime,
    ACTIONS(238), 1,
      sym_name,
    STATE(98), 1,
      aux_sym_fn_decl_repeat1,
    STATE(127), 1,
      sym_param,
  [2453] = 5,
    ACTIONS(236), 1,
      anon_sym_comptime,
    ACTIONS(238), 1,
      sym_name,
    ACTIONS(240), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      aux_sym_fn_decl_repeat1,
    STATE(119), 1,
      sym_param,
  [2469] = 5,
    ACTIONS(236), 1,
      anon_sym_comptime,
    ACTIONS(238), 1,
      sym_name,
    ACTIONS(242), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      aux_sym_fn_decl_repeat1,
    STATE(124), 1,
      sym_param,
  [2485] = 5,
    ACTIONS(236), 1,
      anon_sym_comptime,
    ACTIONS(238), 1,
      sym_name,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
    STATE(97), 1,
      aux_sym_fn_decl_repeat1,
    STATE(122), 1,
      sym_param,
  [2501] = 5,
    ACTIONS(236), 1,
      anon_sym_comptime,
    ACTIONS(238), 1,
      sym_name,
    ACTIONS(246), 1,
      anon_sym_RPAREN,
    STATE(99), 1,
      aux_sym_fn_decl_repeat1,
    STATE(123), 1,
      sym_param,
  [2517] = 5,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    ACTIONS(236), 1,
      anon_sym_comptime,
    ACTIONS(238), 1,
      sym_name,
    STATE(93), 1,
      aux_sym_fn_decl_repeat1,
    STATE(127), 1,
      sym_param,
  [2533] = 5,
    ACTIONS(236), 1,
      anon_sym_comptime,
    ACTIONS(238), 1,
      sym_name,
    ACTIONS(246), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      aux_sym_fn_decl_repeat1,
    STATE(123), 1,
      sym_param,
  [2549] = 5,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
    ACTIONS(250), 1,
      anon_sym_comptime,
    ACTIONS(253), 1,
      sym_name,
    STATE(98), 1,
      aux_sym_fn_decl_repeat1,
    STATE(131), 1,
      sym_param,
  [2565] = 5,
    ACTIONS(236), 1,
      anon_sym_comptime,
    ACTIONS(238), 1,
      sym_name,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      aux_sym_fn_decl_repeat1,
    STATE(126), 1,
      sym_param,
  [2581] = 2,
    ACTIONS(258), 1,
      ts_builtin_sym_end,
    ACTIONS(260), 3,
      anon_sym_pub,
      anon_sym_fn,
      sym_name,
  [2590] = 2,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    ACTIONS(47), 3,
      anon_sym_pub,
      anon_sym_fn,
      sym_name,
  [2599] = 4,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(262), 1,
      sym_name,
    STATE(114), 1,
      aux_sym_constructor_block_repeat1,
    STATE(121), 1,
      sym_constructor_field,
  [2612] = 2,
    ACTIONS(266), 1,
      anon_sym_RBRACE,
    ACTIONS(264), 3,
      anon_sym_pub,
      anon_sym_fn,
      sym_name,
  [2621] = 2,
    ACTIONS(270), 1,
      anon_sym_RBRACE,
    ACTIONS(268), 3,
      anon_sym_pub,
      anon_sym_fn,
      sym_name,
  [2630] = 2,
    ACTIONS(274), 1,
      anon_sym_RBRACE,
    ACTIONS(272), 3,
      anon_sym_pub,
      anon_sym_fn,
      sym_name,
  [2639] = 2,
    ACTIONS(270), 1,
      ts_builtin_sym_end,
    ACTIONS(268), 3,
      anon_sym_pub,
      anon_sym_fn,
      sym_name,
  [2648] = 2,
    ACTIONS(276), 1,
      ts_builtin_sym_end,
    ACTIONS(278), 3,
      anon_sym_pub,
      anon_sym_fn,
      sym_name,
  [2657] = 4,
    ACTIONS(280), 1,
      anon_sym_RBRACE,
    ACTIONS(282), 1,
      sym_name,
    STATE(108), 1,
      aux_sym_constructor_block_repeat1,
    STATE(147), 1,
      sym_constructor_field,
  [2670] = 2,
    ACTIONS(276), 1,
      anon_sym_RBRACE,
    ACTIONS(278), 3,
      anon_sym_pub,
      anon_sym_fn,
      sym_name,
  [2679] = 2,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    ACTIONS(43), 3,
      anon_sym_pub,
      anon_sym_fn,
      sym_name,
  [2688] = 2,
    ACTIONS(266), 1,
      ts_builtin_sym_end,
    ACTIONS(264), 3,
      anon_sym_pub,
      anon_sym_fn,
      sym_name,
  [2697] = 2,
    ACTIONS(258), 1,
      anon_sym_RBRACE,
    ACTIONS(260), 3,
      anon_sym_pub,
      anon_sym_fn,
      sym_name,
  [2706] = 2,
    ACTIONS(274), 1,
      ts_builtin_sym_end,
    ACTIONS(272), 3,
      anon_sym_pub,
      anon_sym_fn,
      sym_name,
  [2715] = 4,
    ACTIONS(262), 1,
      sym_name,
    ACTIONS(285), 1,
      anon_sym_RBRACE,
    STATE(108), 1,
      aux_sym_constructor_block_repeat1,
    STATE(120), 1,
      sym_constructor_field,
  [2728] = 2,
    ACTIONS(289), 1,
      anon_sym_RBRACE,
    ACTIONS(287), 3,
      anon_sym_pub,
      anon_sym_fn,
      sym_name,
  [2737] = 2,
    ACTIONS(289), 1,
      ts_builtin_sym_end,
    ACTIONS(287), 3,
      anon_sym_pub,
      anon_sym_fn,
      sym_name,
  [2746] = 2,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
    ACTIONS(291), 2,
      anon_sym_comptime,
      sym_name,
  [2754] = 1,
    ACTIONS(280), 2,
      anon_sym_RBRACE,
      sym_name,
  [2759] = 2,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    ACTIONS(293), 1,
      anon_sym_COMMA,
  [2766] = 2,
    ACTIONS(295), 1,
      anon_sym_COMMA,
    ACTIONS(297), 1,
      anon_sym_RBRACE,
  [2773] = 2,
    ACTIONS(285), 1,
      anon_sym_RBRACE,
    ACTIONS(295), 1,
      anon_sym_COMMA,
  [2780] = 2,
    ACTIONS(246), 1,
      anon_sym_RPAREN,
    ACTIONS(293), 1,
      anon_sym_COMMA,
  [2787] = 2,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    ACTIONS(293), 1,
      anon_sym_COMMA,
  [2794] = 2,
    ACTIONS(293), 1,
      anon_sym_COMMA,
    ACTIONS(299), 1,
      anon_sym_RPAREN,
  [2801] = 2,
    ACTIONS(301), 1,
      anon_sym_COLON,
    ACTIONS(303), 1,
      anon_sym_EQ,
  [2808] = 2,
    ACTIONS(293), 1,
      anon_sym_COMMA,
    ACTIONS(305), 1,
      anon_sym_RPAREN,
  [2815] = 2,
    ACTIONS(242), 1,
      anon_sym_RPAREN,
    ACTIONS(293), 1,
      anon_sym_COMMA,
  [2822] = 2,
    ACTIONS(150), 1,
      anon_sym_LPAREN,
    STATE(47), 1,
      sym_arg_list,
  [2829] = 1,
    ACTIONS(307), 1,
      sym_name,
  [2833] = 1,
    ACTIONS(309), 1,
      anon_sym_COLON,
  [2837] = 1,
    ACTIONS(293), 1,
      anon_sym_COMMA,
  [2841] = 1,
    ACTIONS(311), 1,
      sym_name,
  [2845] = 1,
    ACTIONS(313), 1,
      sym_name,
  [2849] = 1,
    ACTIONS(315), 1,
      anon_sym_LPAREN,
  [2853] = 1,
    ACTIONS(317), 1,
      anon_sym_else,
  [2857] = 1,
    ACTIONS(319), 1,
      anon_sym_fn,
  [2861] = 1,
    ACTIONS(226), 1,
      sym_name,
  [2865] = 1,
    ACTIONS(321), 1,
      ts_builtin_sym_end,
  [2869] = 1,
    ACTIONS(323), 1,
      anon_sym_COLON,
  [2873] = 1,
    ACTIONS(325), 1,
      sym_name,
  [2877] = 1,
    ACTIONS(327), 1,
      anon_sym_COLON,
  [2881] = 1,
    ACTIONS(329), 1,
      anon_sym_COLON,
  [2885] = 1,
    ACTIONS(331), 1,
      anon_sym_LPAREN,
  [2889] = 1,
    ACTIONS(333), 1,
      anon_sym_LBRACE,
  [2893] = 1,
    ACTIONS(198), 1,
      anon_sym_COLON,
  [2897] = 1,
    ACTIONS(335), 1,
      sym_name,
  [2901] = 1,
    ACTIONS(295), 1,
      anon_sym_COMMA,
  [2905] = 1,
    ACTIONS(337), 1,
      anon_sym_LBRACE,
  [2909] = 1,
    ACTIONS(339), 1,
      anon_sym_LPAREN,
  [2913] = 1,
    ACTIONS(341), 1,
      anon_sym_LPAREN,
  [2917] = 1,
    ACTIONS(343), 1,
      sym_name,
  [2921] = 1,
    ACTIONS(345), 1,
      sym_name,
  [2925] = 1,
    ACTIONS(347), 1,
      anon_sym_fn,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 52,
  [SMALL_STATE(4)] = 104,
  [SMALL_STATE(5)] = 150,
  [SMALL_STATE(6)] = 196,
  [SMALL_STATE(7)] = 242,
  [SMALL_STATE(8)] = 263,
  [SMALL_STATE(9)] = 284,
  [SMALL_STATE(10)] = 326,
  [SMALL_STATE(11)] = 365,
  [SMALL_STATE(12)] = 404,
  [SMALL_STATE(13)] = 429,
  [SMALL_STATE(14)] = 452,
  [SMALL_STATE(15)] = 477,
  [SMALL_STATE(16)] = 498,
  [SMALL_STATE(17)] = 537,
  [SMALL_STATE(18)] = 564,
  [SMALL_STATE(19)] = 597,
  [SMALL_STATE(20)] = 630,
  [SMALL_STATE(21)] = 647,
  [SMALL_STATE(22)] = 664,
  [SMALL_STATE(23)] = 697,
  [SMALL_STATE(24)] = 714,
  [SMALL_STATE(25)] = 747,
  [SMALL_STATE(26)] = 780,
  [SMALL_STATE(27)] = 797,
  [SMALL_STATE(28)] = 814,
  [SMALL_STATE(29)] = 847,
  [SMALL_STATE(30)] = 864,
  [SMALL_STATE(31)] = 881,
  [SMALL_STATE(32)] = 914,
  [SMALL_STATE(33)] = 947,
  [SMALL_STATE(34)] = 980,
  [SMALL_STATE(35)] = 1013,
  [SMALL_STATE(36)] = 1030,
  [SMALL_STATE(37)] = 1063,
  [SMALL_STATE(38)] = 1080,
  [SMALL_STATE(39)] = 1113,
  [SMALL_STATE(40)] = 1146,
  [SMALL_STATE(41)] = 1179,
  [SMALL_STATE(42)] = 1212,
  [SMALL_STATE(43)] = 1245,
  [SMALL_STATE(44)] = 1262,
  [SMALL_STATE(45)] = 1279,
  [SMALL_STATE(46)] = 1312,
  [SMALL_STATE(47)] = 1345,
  [SMALL_STATE(48)] = 1362,
  [SMALL_STATE(49)] = 1395,
  [SMALL_STATE(50)] = 1412,
  [SMALL_STATE(51)] = 1445,
  [SMALL_STATE(52)] = 1478,
  [SMALL_STATE(53)] = 1511,
  [SMALL_STATE(54)] = 1527,
  [SMALL_STATE(55)] = 1555,
  [SMALL_STATE(56)] = 1573,
  [SMALL_STATE(57)] = 1589,
  [SMALL_STATE(58)] = 1617,
  [SMALL_STATE(59)] = 1645,
  [SMALL_STATE(60)] = 1663,
  [SMALL_STATE(61)] = 1693,
  [SMALL_STATE(62)] = 1709,
  [SMALL_STATE(63)] = 1739,
  [SMALL_STATE(64)] = 1766,
  [SMALL_STATE(65)] = 1793,
  [SMALL_STATE(66)] = 1820,
  [SMALL_STATE(67)] = 1847,
  [SMALL_STATE(68)] = 1874,
  [SMALL_STATE(69)] = 1901,
  [SMALL_STATE(70)] = 1928,
  [SMALL_STATE(71)] = 1955,
  [SMALL_STATE(72)] = 1982,
  [SMALL_STATE(73)] = 1997,
  [SMALL_STATE(74)] = 2024,
  [SMALL_STATE(75)] = 2051,
  [SMALL_STATE(76)] = 2078,
  [SMALL_STATE(77)] = 2105,
  [SMALL_STATE(78)] = 2132,
  [SMALL_STATE(79)] = 2159,
  [SMALL_STATE(80)] = 2186,
  [SMALL_STATE(81)] = 2213,
  [SMALL_STATE(82)] = 2240,
  [SMALL_STATE(83)] = 2267,
  [SMALL_STATE(84)] = 2294,
  [SMALL_STATE(85)] = 2308,
  [SMALL_STATE(86)] = 2332,
  [SMALL_STATE(87)] = 2353,
  [SMALL_STATE(88)] = 2374,
  [SMALL_STATE(89)] = 2395,
  [SMALL_STATE(90)] = 2416,
  [SMALL_STATE(91)] = 2437,
  [SMALL_STATE(92)] = 2453,
  [SMALL_STATE(93)] = 2469,
  [SMALL_STATE(94)] = 2485,
  [SMALL_STATE(95)] = 2501,
  [SMALL_STATE(96)] = 2517,
  [SMALL_STATE(97)] = 2533,
  [SMALL_STATE(98)] = 2549,
  [SMALL_STATE(99)] = 2565,
  [SMALL_STATE(100)] = 2581,
  [SMALL_STATE(101)] = 2590,
  [SMALL_STATE(102)] = 2599,
  [SMALL_STATE(103)] = 2612,
  [SMALL_STATE(104)] = 2621,
  [SMALL_STATE(105)] = 2630,
  [SMALL_STATE(106)] = 2639,
  [SMALL_STATE(107)] = 2648,
  [SMALL_STATE(108)] = 2657,
  [SMALL_STATE(109)] = 2670,
  [SMALL_STATE(110)] = 2679,
  [SMALL_STATE(111)] = 2688,
  [SMALL_STATE(112)] = 2697,
  [SMALL_STATE(113)] = 2706,
  [SMALL_STATE(114)] = 2715,
  [SMALL_STATE(115)] = 2728,
  [SMALL_STATE(116)] = 2737,
  [SMALL_STATE(117)] = 2746,
  [SMALL_STATE(118)] = 2754,
  [SMALL_STATE(119)] = 2759,
  [SMALL_STATE(120)] = 2766,
  [SMALL_STATE(121)] = 2773,
  [SMALL_STATE(122)] = 2780,
  [SMALL_STATE(123)] = 2787,
  [SMALL_STATE(124)] = 2794,
  [SMALL_STATE(125)] = 2801,
  [SMALL_STATE(126)] = 2808,
  [SMALL_STATE(127)] = 2815,
  [SMALL_STATE(128)] = 2822,
  [SMALL_STATE(129)] = 2829,
  [SMALL_STATE(130)] = 2833,
  [SMALL_STATE(131)] = 2837,
  [SMALL_STATE(132)] = 2841,
  [SMALL_STATE(133)] = 2845,
  [SMALL_STATE(134)] = 2849,
  [SMALL_STATE(135)] = 2853,
  [SMALL_STATE(136)] = 2857,
  [SMALL_STATE(137)] = 2861,
  [SMALL_STATE(138)] = 2865,
  [SMALL_STATE(139)] = 2869,
  [SMALL_STATE(140)] = 2873,
  [SMALL_STATE(141)] = 2877,
  [SMALL_STATE(142)] = 2881,
  [SMALL_STATE(143)] = 2885,
  [SMALL_STATE(144)] = 2889,
  [SMALL_STATE(145)] = 2893,
  [SMALL_STATE(146)] = 2897,
  [SMALL_STATE(147)] = 2901,
  [SMALL_STATE(148)] = 2905,
  [SMALL_STATE(149)] = 2909,
  [SMALL_STATE(150)] = 2913,
  [SMALL_STATE(151)] = 2917,
  [SMALL_STATE(152)] = 2921,
  [SMALL_STATE(153)] = 2925,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(136),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(140),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(139),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(132),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(148),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arg_list_repeat1, 2), SHIFT_REPEAT(19),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2), SHIFT_REPEAT(6),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arg_list_repeat1, 2), SHIFT_REPEAT(33),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2), SHIFT_REPEAT(146),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arg_list_repeat1, 2), SHIFT_REPEAT(148),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arg_list_repeat1, 2), SHIFT_REPEAT(20),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2), SHIFT_REPEAT(20),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arg_list_repeat1, 2), SHIFT_REPEAT(21),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 3),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(132),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 2),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 2),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 1),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constructor_block, 3),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constructor_block, 3),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 3),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_list, 3),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 4),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 4),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constructor_block, 4),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constructor_block, 4),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 4),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_list, 4),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constructor_block, 2),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constructor_block, 2),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 9),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expr, 9),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 2),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_list, 2),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_, 7),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_, 7),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 3),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_, 5),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_, 5),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constructor_field, 3),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_param, 4),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stmt, 1),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt, 1),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_arg_list_repeat1, 2),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [202] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(153),
  [205] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(151),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [210] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(141),
  [213] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(136),
  [216] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(140),
  [219] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(139),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(153),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(151),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(141),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(142),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fn_decl_repeat1, 2),
  [250] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fn_decl_repeat1, 2), SHIFT_REPEAT(129),
  [253] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_fn_decl_repeat1, 2), SHIFT_REPEAT(142),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_decl, 4),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_decl, 4),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn_decl, 9),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_decl, 9),
  [268] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn_decl, 8),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_decl, 8),
  [272] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn_decl, 7),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_decl, 7),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_decl, 6),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn_decl, 6),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_constructor_block_repeat1, 2),
  [282] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_constructor_block_repeat1, 2), SHIFT_REPEAT(145),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [287] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decl, 1),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decl, 1),
  [291] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_fn_decl_repeat1, 2),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [321] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_zeque(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
